const Actions = {
    SET_SEARCH:'SET_SEARCH',
    GET_DATA_PENDING:'GET_DATA_PENDING',
    GET_DATA_SUCCESS:'GET_DATA_SUCCESS',
    GET_DATA_FAILURE:'GET_DATA_FAILURE',
    SET_FINAL_DATA:'SET_FINAL_DATA'
};

export default Actions;